# Site settings
title: Evolute
baseurl: "evolutee" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
paginate: 2
paginate_path: /blog/page:num/
